### ISSUE TITLE
我知道好几个前端大佬也都辞职当自由职业者了。

### ISSUE THREAD

**Issue by puxiao** [shengxinjing/self-employed-workbook#3]
比如，半月前从字节辞职的 卡颂 (公众号：魔术师卡颂)
还有几个月前的 波神 (公众号：这波能反杀)
> 这 2 位都已和出版社签订合同，要各自写一本前端书籍

还有 公众号：脑洞前端 的作者

**Comment by shengxinjing** [comment]
感谢推荐，去关注一波波神
